stages:
  - quality

image: node:lts-alpine

cache:
  paths:
    - node_modules/

test:
  stage: quality
  script: 
    - npm install
    - npm run test

lint:
  stage: quality
  script: 
    - npm install
    - npm run lint




