stages:
  - quality
  - release

image: node:lts-alpine

cache:
  paths:
    - node_modules/

test:
  stage: quality
  script: 
    - npm install
    - npm run test

lint:
  stage: quality
  script: 
    - npm install
    - npm run lint

release:
  stage: release
  only:
    - tags
  script:
    - npm install
    - npm run build
    - tar -czvf web-audio-recorder-${CI_COMMIT_TAG}.tar.gz ./build
    - node ./ci/generateRelease.js web-audio-recorder-${CI_COMMIT_TAG}.tar.gz