stages:
  - quality
  - release

image: node:lts-alpine

cache:
  paths:
    - node_modules/

test:
  stage: quality
  script: 
    - npm install
    - npm run test

lint:
  stage: quality
  script: 
    - npm install
    - npm run lint

release:
  stage: release
  only:
    - tags
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build